### ISSUE TITLE
升级到了pip 7.0.0出问题了

### ISSUE THREAD

**Issue by hueyless** [yxjxx/v2ex_daily_mission#1]
Traceback (most recent call last):
  File "/usr/local/bin/v2ex", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests

**Comment by hueyless** [comment]
distribute 升级到 0.7.3 解决了
